apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-demo--deployment
  namespace: spring-boot-demo--namespace
spec:
  replicas: 5
  selector:
    matchLabels:
      app: spring-boot-demo--selector-label-app
  template:
    metadata:
      labels:
        app: spring-boot-demo--selector-label-app
    spec:
      containers:
        - name: spring-boot-demo--deployment-container
          image: huntercodexs/spring-boot-demo:latest
          ports:
            - containerPort: 38087
