apiVersion: v1
kind: Service
metadata:
  name: spring-boot-demo--service
  namespace: spring-boot-demo--namespace
spec:
  selector:
    app: spring-boot-demo--selector_app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 38087
  type: LoadBalancer
